#!/bin/env python
# -------------------------------------------------------
# Compiled By RC Chuah-(RaynerSec)
# Github : https://github.com/rc-chuah
# Github : https://github.com/RaynerSec
# -------------------------------------------------------
# Platform : Linux
# Time : Tue Sep 1 17:02:02 2020
# -------------------------------------------------------

exec(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('IyEvYmluL2VudiBweXRob24KIyAtKi0gY29kaW5nOiB1dGYtOCAtKi0gIwojIENyZWF0ZWQgQW5kIENvZGVkIGJ5IFJDIENodWFoLShSYXluZXJTZWMpCgojIEltcG9ydCBNb2R1bGVzCmltcG9ydCBvcwppbXBvcnQgc3lzCmltcG9ydCB0aW1lCmltcG9ydCBkYXRldGltZQoKb3Muc3lzdGVtKCJjbGVhciIpCgojIEluZm9ybWF0aW9uCnByaW50KCJLYWxpLU5ldGh1bnRlci1Jbi1UZXJtdXggSW5zdGFsbGVyIikKcHJpbnQoIiIpCnByaW50KCJTY3JpcHQgQnkgUkMgQ2h1YWgiKQpwcmludCgiIikKbm93ID0gZGF0ZXRpbWUuZGF0ZXRpbWUubm93KCkKcHJpbnQoIkN1cnJlbnQgZGF0ZSBhbmQgdGltZSA6ICIpCnByaW50KG5vdy5zdHJmdGltZSgiJWQtJW0tJVkgJUg6JU06JVMiKSkKcHJpbnQoIiIpCnByaW50KCJbMV0tSW5zdGFsbCBLYWxpIE5ldGh1bnRlciBJbiBUZXJtdXggRnVsbCBWZXJzaW9uIikKcHJpbnQoIlsyXS1JbnN0YWxsIEthbGkgTmV0aHVudGVyIEluIFRlcm11eCBNaW5pbWFsIFZlcnNpb24iKQpwcmludCgiWzNdLVVuaW5zdGFsbCBLYWxpIE5ldGh1bnRlciBJbiBUZXJtdXgiKQpwcmludCgiWzRdLUV4aXQgSW5zdGFsbGVyIikKcHJpbnQoIiIpCgojIE1haW4KY2hvaWNlID0gaW5wdXQoIkNob2ljZTogIikKaWYgY2hvaWNlID09ICIxIjoKCW9zLnN5c3RlbSgiY2QgJHtIT01FfSAmJiBjdXJsIC1mc1NMIGh0dHBzOi8vYml0LmRvL2ZOeXNvIHwgYmFzaCAmJiBybSAtcmYga2FsaWZzLWFybWhmLWZ1bGwudGFyLnh6ICYmIHJtIC1yZiBrYWxpZnMtYXJtNjQtZnVsbC50YXIueHogJiYgcm0gLXJmIGthbGlmcy1hcm1oZi1mdWxsLnNoYTUxMnN1bSAmJiBybSAtcmYga2FsaWZzLWFybTY0LWZ1bGwuc2hhNTEyc3VtIikKaWYgY2hvaWNlID09ICIyIjoKCW9zLnN5c3RlbSgiY2QgJHtIT01FfSAmJiBjdXJsIC1mc1NMIGh0dHBzOi8vYml0LmRvL2ZOeXNXIHwgYmFzaCAmJiBybSAtcmYga2FsaWZzLWFybWhmLW1pbmltYWwudGFyLnh6ICYmIHJtIC1yZiBrYWxpZnMtYXJtNjQtbWluaW1hbC50YXIueHogJiYgcm0gLXJmIGthbGlmcy1hcm1oZi1taW5pbWFsLnNoYTUxMnN1bSAmJiBybSAtcmYga2FsaWZzLWFybTY0LW1pbmltYWwuc2hhNTEyc3VtIikKaWYgY2hvaWNlID09ICIzIjoKCW9zLnN5c3RlbSgicm0gLXJmICR7SE9NRX0va2FsaS1hcm02NCAmJiBybSAtcmYgJHtIT01FfS9rYWxpLWFybWhmICYmIHJtIC1yZiAke1BSRUZJWH0vYmluL25oICYmIHJtIC1yZiAke1BSRUZJWH0vYmluL25ldGh1bnRlciAmJiBzbGVlcCAxICYmIGVjaG8gWytdIFN1Y2Nlc3NmdWxseSBVbmluc3RhbGxlZCAuLi4iKQppZiBjaG9pY2UgPT0gIjQiOgoJc3lzLmV4aXQoKQplbGlmIGNob2ljZSA9PSAiIjoKICAgIHByaW50KCJZb3UgSGF2ZW4ndCBTZWxlY3QgQW55IE9wdGlvbiBGcm9tIFRoZSBBYm92ZSAhISEiKQogICAgcHJpbnQoIlBsZWFzZSBSdW4gVGhpcyBTY3JpcHQgQWdhaW4gISEhIik=')[0]))
